### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by raphamorim** [SnowflakePowered/librashader#142]
Hey there, thanks for the amazing project. I was going to start write something similar (at least only for wgpu) to this until someone told me that this project exists.

I would like to integrate it with Rio terminal (https://github.com/raphamorim/rio/pull/714), but my understanding is that Rio would need be licensed under same license as librashader?

Thank you in advance

**Comment by chyyran** [comment]
That’s incorrect. Your only requirements under MPL2 are to provide sources of modified files of librashader.

You are allowed to use the unmodified crate and binaries as part of any work under any license, commercial or otherwise.

**Comment by raphamorim** [comment]
Ah thank you @chyyran for clarifying it 🙏 will be proceeding with the pr then
