### ISSUE TITLE
`OriginalAspect`, `OriginalAspectRot`, `FrameTimeDelta`, `OriginalFPS`

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/librashader#145]
* Bump API to `2` for the addition of  `frame_options.aspect_ratio`.
* Add `#define _HAS_ORIGINALASPECT_UNIFORMS ` to preprocessing
* Add `#define _HAS_FRAMETIME_UNIFORMS` to preprocessing

* For APIs before `2`,  `frame_options.aspect_ratio` will default to [what is some reasonable default? 1.33?] 
  * The Rust API has no concept of API versioning so we can't not provide those uniforms.
* The uniform `CoreAspect` will be provided as `frame_options.aspect_ratio`
* The uniform `CoreAspectRot` is calculated as follows
  * If `frame_options.rotation` is `1` or `3` (mod 4), then `CoreAspectRot` will be provided as (`1/frame_options.aspect_ratio`)
  * Otherwise, `CoreAspectRot`  will be provided as `frame_options.aspect_ratio`

**Comment by chyyran** [comment]
If `#define _HAS_COREASPECT_UNIFORMS` is the only way to query uniforms then we'll need another overload for `libra_preset_create`.

Something like `libra_preset_create_with_options`, where options looks like 

```
#[repr(C)]
#[derive(Default, Debug, Clone)]
pub struct libra_preset_opt_t {
    /// The librashader API version.
    pub version: LIBRASHADER_API_VERSION, 
    /// The wildcard context to provide to the shader preset.
    /// If this is null, will use the default context.
    pub context: *mut libra_preset_ctx_t,
    /// Enables `_HAS_COREASPECT_UNIFORMS` behaviour.
    /// If this is true, then `frame_options.aspect_ratio` must be set for correct behaviour of shaders.
    /// This is only supported on API 2 and above, otherwise this has no effect.
    pub has_core_aspect: bool
}
```

**Comment by chyyran** [comment]
or should we just estimate it with originalsize for api1?

**Comment by HyperspaceMadness** [comment]
Hi @chyyran I just wanted to leave a note that OriginalAspectRot has been renamed to OriginalAspectRotated

**Comment by chyyran** [comment]
Thanks @HyperspaceMadness for the heads up, currently waiting for the frametime PR to get merged in RetroArch before starting on this

**Comment by HyperspaceMadness** [comment]
Awesome! That's going to be a great feature!

By the way fantastic job on this library, it's also really amazing the speed up you were able to achieve on loading in dx11 with the caching

I'm curious if you could point me to any open source examples of integrating Librashader

**Comment by chyyran** [comment]
Probably the most prominent examples are [ares](https://github.com/ares-emulator/ares) and via the Rust API [Rio terminal](https://github.com/raphamorim/rio). There’s also a couple of small emulators written in Rust that use the Rust API.
