### ISSUE TITLE
Preset path wildcard replacement

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/librashader#16]
Implement path wildcard replacement from https://github.com/libretro/RetroArch/pull/15023

It remains to be seen whether or not presets will use these wildcards but librashader should eventually add support for them via a context object if they see common use.

Some wildcards can be inferred from when loading from path.

* `$VID-DRV-SHADER-EXT$` is always `.slang` for librashader.
* `$VID-DRV-PRESET-EXT$` is always `.slangp` for librashader.
* `$PRESET_DIR$` can be inferred at load time.
* `$PRESET$` can be inferred at load time.

The remaining wildcards can be represented with structs; this gives a the context object that can be `#[repr(C)]`.

* `$VID_DRIV$` is a static enum
   ```rust
    #[repr(C)]
    pub enum GraphicsRuntime {
        OpenGL = 0,
        Vulkan = 1,
        Direct3D11 = 2,
        Direct3D12 = 3
    } 
    ``` 
* `$CORE-REQ-ROT$`, `$VID-USER-ROT$`, `$SCREEN-ORIENT$` can be represented by an integer mod 4 as quarter-rotations on the unit circle (i.e. 0 = 0, 1 = 90deg, 2 = 180deg, 3 = 270deg).
* `$VID-FINAL-ROT$` is calculated as the sum of `$CORE-REQ-ROT$` and  `$VID-USER-ROT$`.
* `$VIEW-ASPECT-ORIENT$`,  `$CORE-ASPECT-ORIENT$` , `$VID-ALLOW-CORE-ROT$` will be encoded as booleans.
* `$CORE$` , `$GAME$`, and `$CONTENT-DIR$` will have to be parsed from C strings owned by the caller.

Example C struct definition:

```c
struct libra_context_t {
  LIBRA_RUNTIME runtime;
  uint8_t core_rotation;
  uint8_t user_rotation;
  bool core_aspect_vertical;
  bool view_aspect_vertical;
  bool allow_core_rotation;
  char* core_name;
  char* game_name;
  char* context_directory;
}
```

Because paths are canonicalized, this information needs to be available at preset parse time.

**Comment by HyperspaceMadness** [comment]
This sounds really great!!! I'm curious if you have support for the reference chaining and params files what I put into Retroarch. feel free to contact me on the libretro forum, or at HyperspaceMadness@outlook.com I have some ideas I'd like to discuss with you if you are interested :)

**Comment by chyyran** [comment]
Reference chains and params files should already work with similar
resolution logic as RetroArch.
