### ISSUE TITLE
Librashader.lib not being compiled as static

### ISSUE THREAD

**Issue by star69rem** [SnowflakePowered/librashader#20]
I'm not able to link librashader.lib with a Visual Studio project with MT_StaticRelease. 

I get the following error when setting the crt-static environment variable (SET RUSTFLAGS=-Ctarget-feature=+crt-static):

librashader.lib(wrapper.o) has value MT_StaticRelease
librashader.lib(shaderc.obj) has value MD_DynamicRelease

Is some librashader dependency dynamic or something?

**Comment by chyyran** [comment]
librashader-reflect uses https://github.com/google/shaderc-rs which builds as dynamic by default. You could try enabling the `standalone` cargo feature in librashader-reflect which should build shaderc from source.


If that doesn't work you'll have to do some digging. librashader is designed to be linked dynamically with `librashader_ld.h`, since theres so many moving parts I can't really accommodate for every static linking scenario.

**Comment by chyyran** [comment]
Are you using the nightly compiler?

**Comment by star69rem** [comment]
Yes. It compiles fine if I don't try to build it static MT.

**Comment by chyyran** [comment]
Is there a pressing reason why you need a static build and can’t use
librashader_ld.h?

**Comment by star69rem** [comment]
If there wasn't I wouldn't be going through this BDSM.

**Comment by chyyran** [comment]
I'm going to need to know more about your use case as to why the supported headers aren't a valid option.

**Comment by star69rem** [comment]
I don't want users to have to install the C++ Redistributables. Thanks!

**Comment by chyyran** [comment]
While I honestly don’t think it’s worth the trouble of static linking just to avoid installing the C++ redistributables (especially since librashader_ld.h means that the librashader version is user-upgradable), I can look into this for you; just in the middle of a move right now so it’ll be some time until I can get set up again.

**Comment by star69rem** [comment]
I would appreciate it but there's no rush. I just keep running into people who get tripped up by the redistributables and I would really prefer to not have to package a whole installer for it. Thanks again!

**Comment by chyyran** [comment]
https://github.com/google/shaderc-rs/pull/143

looks like I'll need this, will need to wait until the next shaderc release to get this working.

**Comment by chyyran** [comment]
Could you check if shaderc links properly as of 2bd6f8f80ff4293200f371216becc3bc69df2f07?

**Comment by chyyran** [comment]
Publishing librashader `0.2.0-beta.1` for you to test. I removed DXIL support on Linux, hence the minor bump.

**Comment by star69rem** [comment]
Get this error:

3>lld-link : error : /failifmismatch: mismatch detected for 'RuntimeLibrary':
3>>>> libcpmt.lib(xtime.obj) has value MT_StaticRelease
3>>>> librashader.lib(wrapper.o) has value MD_DynamicRelease

**Comment by star69rem** [comment]
Output from shaderc-sys build:
cargo:warning=shaderc: searching native shaderc libraries in Vulkan SDK 'C:\VulkanSDK\1.3.236.0/lib'
cargo:warning=shaderc: Windows MSVC static build is experimental
cargo:rustc-link-search=native=\\?\C:\VulkanSDK\1.3.236.0\Lib
cargo:rustc-link-lib=static=shaderc_combined

**Comment by star69rem** [comment]
I got it to compile by just moving the shaderc libs out of the vulkan SDK folder.

**Comment by star69rem** [comment]
Still having one problem: it all works if it's using the optimized profile, but using the debug profile doesn't work because it seems like some stuff is still being compiled in release mode. So it seems like the debug setting isn't being passed to all dependencies?

**Comment by star69rem** [comment]
2>>>> libcpmtd.lib(xstoull.obj) has value 2
2>>>> librashader_debug.lib(wrapper.o) has value 0

xstoull.obj for some reason is in release

**Comment by star69rem** [comment]
I tried the recommendation to set the environment variables: SET CXXFLAGS=-MTd SET CFLAGS=-MTd

Now it fails on xstrxfrm.obj instead of xstoull.obj.

1>>>> libcpmtd.lib(xstrxfrm.obj) has value 2
1>>>> librashader_debug.lib(shaderc.cc.obj) has value 0

**Comment by chyyran** [comment]
I'm honestly not sure where libcpmtd.lib is coming from. Maybe [spirv-to-dxil-rs](https://github.com/SnowflakePowered/spirv-to-dxil-rs/blob/master/spirv-to-dxil-sys/native/CMakeLists.txt)? Does it build without `dxil` support?

**Comment by star69rem** [comment]
I looked into it a bit, and apparently this is a known issue with rust's libc being hardcoded to compile with a release flag. I'm not even sure there's anything you can do. Seems like it's been an issue for years.

https://github.com/rust-lang/rust/issues/39016

I worked around it by just throwing in some preprocessor definitions to use the DLL for debug mode and the static linking for the release build. Not ideal, but it works.

**Comment by chyyran** [comment]
Closing as resolved.
