### ISSUE TITLE
Storing DLL inside application

### ISSUE THREAD

**Issue by cruduxcru0** [SnowflakePowered/librashader#25]
Hi,

I have for some time being writing a libretro client. I am curious whether the license allows for me storing the librashader DLL as a compressed DLL blob inside the client. My client has capabilities for Windows PE loader emulation, so that DLLs and thus libretro cores can be loaded directly from memory or archive files (such as 7z), without extracting to disk at all.

I am wondering would in your opinion the license allow for linking the DLL as such a binary blob for the PE loader emulator to resolve imports, etc? Or should I just store it as a 7z?

**Comment by chyyran** [comment]
Thanks for asking! Yes, MPLv2 is compatible with this use case. The only requirement is to put a license and copyright notice for librashader. There are in general no linking restrictions, the virality of GPL doesn't apply (unless you choose GPL for some reason) and my intentions with the license are to ensure improvements get upstreamed.

**Comment by chyyran** [comment]
Just as a reminder, the [necessary headers for linking to librashader](https://github.com/SnowflakePowered/librashader/tree/master/include) are explicitly licensed under MIT to avoid any chance of virality, even though MPL2 already isn't viral even when linking statically.

**Comment by cruduxcru0** [comment]
Awesome, problem solved.
