### ISSUE TITLE
Is it possible to integrate librashader (LS) into Zelda Classic (ZC)?

### ISSUE THREAD

**Issue by fm3845w0** [SnowflakePowered/librashader#28]
ZC is an open implementation of the NES Zelda engine for which fans developed a massive catalog of over 500 quests. It's older than > 40% of the population, outsizes the entire N64 library, and is home to to the undisputedly biggest fan scene for Zelda dev on the planet.

Here's one index to some ZC quests, many of which outshine the quality of the base game:

https://www.purezc.net/index.php?page=quests&sort=hits

After nearly a quarter century, the much-anticipated v3.0 nears completion. Google Chrome dev Connor's outstanding ZC modernizations may now make LS integrable, a win for both projects and for the players. If so and if a shader guru will offer a tailored "Getting Started" primer, pull requests, or other tips to ZC devs, I opened an issue on ZC's tracker and request your wisdom there:

https://github.com/ZQuestClassic/ZQuestClassic/issues/899

If LS isn't fit for this project, I request guidance on the next best path forward.

**Comment by chyyran** [comment]
librashader is compatible with anything that draws to a GPU quad with OpenGL, DirectX, or Vulkan. Whether or not its suitable for use in Zelda Classic depends on the developers over there. While librashader does do the “heavy lifting” there are auxiliary parts to it that may not be trivial to implement such as UI for selecting shaders.

I would be happy to take more technical questions from the devs should they be inclined to investigate librashader.
