### ISSUE TITLE
Some shaders output corrupted textures in DirectX 11

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/librashader#7]
This is scalefx\scalefx-9x.slangp in Retroarch:
![image](https://user-images.githubusercontent.com/109876913/215547622-4a356b5a-35bf-42d1-a0a0-11c5850e521c.png)

Here it is in Librashader:
![image](https://user-images.githubusercontent.com/109876913/215547801-795a3de5-c15f-433a-b092-e509d8b8f1b9.png)

_Originally posted by @star69rem in https://github.com/SnowflakePowered/librashader/discussions/2#discussioncomment-4821309_

**Comment by chyyran** [comment]
RenderDoc caps: 

https://archive.org/details/scalefx-aa-capture1
https://archive.org/details/zfast-crt-capture1

**Comment by chyyran** [comment]
ScaleFX issue is due to preset overriding framebuffer format to float.

zfast is potentially due to DX11 not setting blend state, which is fixed in https://github.com/SnowflakePowered/librashader/commit/5ffcf005a0920c9e2166078ddc9d677cc48f4492. 

Waiting on @star69rem to report back before confirming.

**Comment by star69rem** [comment]
Nvwgf2umx.pdb not loaded error when running scalefx.

**Comment by star69rem** [comment]
crt royale crashes now too.

**Comment by star69rem** [comment]
Do I need to replace the includes? Were there changes that would break things there?

**Comment by star69rem** [comment]
Exception thrown at 0x00007FFFF9FD352C (nvwgf2umx.dll) in .exe: 0xC0000005: Access violation reading location 0x0000000000000000.

**Comment by star69rem** [comment]
The crashing is inconsistent. It actually ran once. Seems like it crashes on filter_chain_create. Interestingly, crt royale is WAY faster than it was before. I get full speed now.

**Comment by chyyran** [comment]
Closing this as fixed by the blend state issue patches. We can continue discussion on crashing issues in the discussion thread. https://github.com/SnowflakePowered/librashader/discussions/2
