### ISSUE TITLE
Lack of code examples

### ISSUE THREAD

**Issue by Azq2** [SnowflakePowered/librashader#88]
1. Are there any projects that use librashade? It would be cool to post a list of such projects directly in the readme. I couldn't find it right away by searching on github.

2. Is it possible to get maximum resolution from the pipeline output?
  
    For e.g. `../slang-shaders/edge-smoothing/xbrz/shaders/2xbrz.slang`
    
    Input size - 128x128 <-- known value
    Output size - 256x256 <-- I need this

4. How to access the list of `#pragma parameters` and the ability to change them?

**Comment by Azq2** [comment]
My current solution for #2
```rust

unsafe fn calc_output_size(shader_path: &str, original_size: Size<u32>) -> Size<u32> {
	let preset = ShaderPreset::try_parse_with_driver_context(shader_path, VideoDriver::GlCore).unwrap();

	let mut iterator = preset.shaders.iter().enumerate().peekable();
	let mut target_size = original_size;

	while let Some((_index, shader_config)) = iterator.next() {
		let next_size = scale_pass::<u32>(
			shader_config.scaling.clone(),
			target_size,
			target_size,
			original_size,
		);
		target_size = next_size;
	}

	return target_size;
}

// From librashader-runtime/src/scaling.rs
fn scale_pass<T>(scaling: Scale2D, source: Size<T>, viewport: Size<T>, original: Size<T>) -> Size<T>
where
	T: Mul<ScaleFactor, Output = f32> + Copy + Ord + 'static,
	f32: AsPrimitive<T>,
{
	const MAX_TEXEL_SIZE: f32 = 16384f32;

	let width = match scaling.x {
		Scaling {
			scale_type: ScaleType::Input,
			factor,
		} => source.width * factor,
		Scaling {
			scale_type: ScaleType::Absolute,
			factor,
		} => factor.into(),
		Scaling {
			scale_type: ScaleType::Viewport,
			factor,
		} => viewport.width * factor,
		Scaling {
			scale_type: ScaleType::Original,
			factor,
		} => original.width * factor,
	};

	let height = match scaling.y {
		Scaling {
			scale_type: ScaleType::Input,
			factor,
		} => source.height * factor,
		Scaling {
			scale_type: ScaleType::Absolute,
			factor,
		} => factor.into(),
		Scaling {
			scale_type: ScaleType::Viewport,
			factor,
		} => viewport.height * factor,
		Scaling {
			scale_type: ScaleType::Original,
			factor,
		} => original.height * factor,
	};

	Size {
		width: std::cmp::min(
			std::cmp::max(width.round().as_(), 1f32.as_()),
			MAX_TEXEL_SIZE.as_(),
		),
		height: std::cmp::min(
			std::cmp::max(height.round().as_(), 1f32.as_()),
			MAX_TEXEL_SIZE.as_(),
		),
	}
}
```

**Comment by chyyran** [comment]
1. The only open source project that I know of using librashader is [ares](https://github.com/ares-emulator/ares). There's a few closed source projects that I know of too. There is a hello triangle example for every runtime in the `tests` folder.

2. There is no API for this. The final pass is drawn to an arbitrarily sized viewport, and scaling needs to account for the viewport size. That is to say the output size is always relative to three variables, the original input size, the size of the previous frame, and the viewport size. 

3. Use the `preset` API https://docs.rs/librashader/0.2.8/librashader/presets/index.html
